In [ ]:
import pandas as pd
sample_input=pd.read_csv("Prefer city - input.csv")
population_data=pd.read_csv("Prefer city - cd_demo_race_economics(1).csv")

In [ ]:
sample_input

,ID,Zipcode,Age,Annual Income,Ethnicity,Feedback Option,Feedback Details
0,1,11101,18 - 24,20000-30000,White alone,Redesign,NaN
1,2,11102,35 - 44,50000-60000,Black or African American alone,Keep as is,NaN
2,3,11106,25 - 34,30000-40000,Hispanic,Redesign,NaN
3,4,11101,18 - 24,20000-30000,Asian alone,Other Suggestion,Add more benches
4,5,11102,55 - 64,80000-90000,White alone,Redesign,NaN
...,...,...,...,...,...,...,...
148,149,11106,25 - 34,30000-40000,Asian alone,Other suggestion,More lighting
149,150,11106,35 - 44,40000-50000,African American,Keep as is,NaN
150,151,11106,18 - 24,20000-30000,Hispanic or Latino,Redesign,NaN
151,152,11106,55 - 64,60000-70000,White alone,Other suggestion,Install a fountain
152,153,11106,25 - 34,30000-40000,Asian alone,Keep as is,NaN

In [ ]:
sample_input.dropna(subset=['ID'], inplace=True)
sample_input.drop(sample_input.index[-1], inplace=True)
sample_input['ID'] = sample_input['ID'].astype(int)
sample_input['Zipcode'] = sample_input['Zipcode'].astype(int)
sample_input['Age'] = sample_input['Age'].astype('category')
sample_input['Annual Income'] = sample_input['Annual Income'].astype('category')
sample_input['Ethnicity'] = sample_input['Ethnicity'].astype('category')
sample_input['Feedback Option'] = sample_input['Feedback Option'].astype('category')
sample_input['Feedback Details'] = sample_input['Feedback Details'].astype('object')

In [ ]:
filtered_data = sample_input[sample_input['Zipcode'] == 11101]
race_proportions = filtered_data['Ethnicity'].value_counts(normalize=True)
print(race_proportions)

White alone                                            0.274510
Hispanic                                               0.254902
Asian alone                                            0.196078
Black or African American alone                        0.156863
Hispanic or Latino                                     0.039216
Hispanic/Latino                                        0.039216
Black or African American alone or African American    0.019608
Black or African American alone/African American       0.019608
African American                                       0.000000
Name: Ethnicity, dtype: float64

In [ ]:
summed_race_proportions = pd.Series({
    'White alone': race_proportions['White alone'],
    'Hispanic': race_proportions['Hispanic'],
    'Asian alone': race_proportions['Asian alone'],
    'Black or African American alone': race_proportions['Black or African American alone'],
    'Other': race_proportions[['Black or African American alone or African American', 'Black or African American alone/African American','African American', 'Hispanic or Latino', 'Hispanic/Latino']].sum()
})

print(summed_race_proportions)

White alone                        0.274510
Hispanic                           0.254902
Asian alone                        0.196078
Black or African American alone    0.156863
Other                              0.117647
dtype: float64

In [ ]:
import pandas as pd

# Create a Series with the given data
data = pd.Series([0.274510, 0.254902, 0.196078, 0.156863, 0.117647], index=['White alone', 'Hispanic', 'Asian alone', 'Black or African American alone', 'Other'])

# Convert the Series to a DataFrame by transposing it
sample_df = pd.DataFrame(data).T

sample_df

,White alone,Hispanic,Asian alone,Black or African American alone,Other
0,0.27451,0.254902,0.196078,0.156863,0.117647

In [ ]:
population_data

,cd_name,cd_number,borough,pct_foreign_born,moe_foreign_born,lep_rate,moe_lep_rate,pct_white_nh,pct_black_nh,pct_asian_nh,...,pct_hh_rent_burd,moe_hh_rent_burd,pct_bach_deg,moe_bach_deg,unemployment,moe_unemployment,mean_commute,moe_mean_commute,crime_count,crime_per_1000
0,Bronx Community District 1,201,Bronx,29.3,1.6,29.5,1.6,2.1,28.8,0.5,...,49.4,2.1,11.3,1.0,6.4,0.8,42.5,2.5,2205,21.7
1,Bronx Community District 2,202,Bronx,34.6,1.8,30.6,1.8,1.9,28.4,1.1,...,53.8,2.5,14.2,1.2,6.4,0.8,44.9,2.9,864,12.3
2,Bronx Community District 3,203,Bronx,31.7,1.3,25.9,1.3,1.2,35.8,0.8,...,48.0,2.0,14.1,1.1,6.6,0.7,43.9,2.6,1495,13.6
3,Bronx Community District 6,206,Bronx,32.6,1.5,27.5,1.5,6.1,27.0,1.3,...,55.1,2.0,12.6,1.1,8.4,0.8,44.4,2.4,1312,12.0
4,Bronx Community District 4,204,Bronx,42.7,1.3,35.8,1.4,1.9,28.7,1.3,...,54.0,1.7,15.8,1.0,6.4,0.6,41.9,1.8,2359,14.6
5,Bronx Community District 5,205,Bronx,42.3,1.3,36.2,1.4,1.3,26.6,1.1,...,58.2,1.7,11.8,0.9,7.3,0.7,43.5,1.9,1675,12.2
6,Bronx Community District 7,207,Bronx,44.0,1.5,36.3,1.5,6.6,15.3,5.3,...,53.8,1.7,17.0,0.9,7.2,0.7,45.0,2.0,1900,11.2
7,Bronx Community District 8,208,Bronx,33.3,1.7,20.7,1.4,33.2,12.7,4.1,...,45.1,2.3,40.9,1.2,5.0,0.6,46.4,2.2,961,8.9
8,Bronx Community District 9,209,Bronx,32.7,1.2,24.6,1.1,2.7,29.1,6.6,...,49.0,1.7,17.2,0.9,6.0,0.5,46.2,1.9,1783,9.4
9,Bronx Community District 10,210,Bronx,22.4,1.3,14.7,1.3,26.4,23.2,5.2,...,40.2,2.7,27.0,1.3,4.3,0.6,44.6,2.5,1121,8.6
10,Bronx Community District 11,211,Bronx,33.9,1.2,23.7,1.2,20.5,21.7,7.5,...,49.4,2.1,24.0,1.0,6.0,0.6,43.9,1.9,1043,7.5
11,Bronx Community District 12,212,Bronx,37.5,1.1,11.6,0.9,6.2,60.7,3.2,...,48.8,2.0,23.9,1.0,6.0,0.5,47.8,2.0,2022,9.5
12,Brooklyn Community District 1,301,Brooklyn,21.5,0.8,20.8,1.0,61.3,5.8,6.3,...,40.7,1.5,47.0,1.0,4.0,0.5,34.3,1.0,2056,10.9
13,Brooklyn Community District 2,302,Brooklyn,19.7,0.8,7.2,0.6,50.1,21.3,10.2,...,29.9,1.4,67.1,0.8,4.4,0.4,33.8,0.9,2105,12.9
14,Brooklyn Community District 3,303,Brooklyn,20.4,0.9,9.7,0.7,21.5,53.8,3.8,...,44.3,1.5,36.3,1.0,5.4,0.5,41.6,1.3,2717,15.3
15,Brooklyn Community District 4,304,Brooklyn,32.6,1.4,25.9,1.3,18.3,18.0,5.4,...,49.1,1.9,28.6,1.2,5.3,0.5,41.8,1.7,1600,14.1
16,Brooklyn Community District 5,305,Brooklyn,35.7,1.0,14.9,0.8,3.4,55.2,3.6,...,50.8,1.7,14.6,0.8,4.7,0.4,45.0,1.7,3423,18.0
17,Brooklyn Community District 6,306,Brooklyn,16.5,0.8,6.3,0.6,61.6,9.6,6.8,...,27.7,1.7,70.8,0.8,4.2,0.5,38.0,1.1,921,7.0
18,Brooklyn Community District 7,307,Brooklyn,43.3,1.0,43.6,1.4,27.6,2.7,28.6,...,45.4,1.8,35.0,0.9,3.8,0.4,43.0,1.4,1192,7.8
19,Brooklyn Community District 8,308,Brooklyn,29.5,1.2,6.7,0.7,27.4,52.8,4.1,...,41.8,1.8,45.1,1.2,4.6,0.5,41.2,1.5,1140,9.4
20,Brooklyn Community District 9,309,Brooklyn,39.9,1.3,9.9,1.0,22.9,63.7,1.9,...,48.5,1.9,31.4,1.2,5.4,0.6,42.8,1.7,1044,8.4
21,Brooklyn Community District 10,310,Brooklyn,40.9,0.9,31.4,1.2,49.5,2.5,26.5,...,44.4,1.8,38.3,0.8,4.0,0.4,44.4,1.4,753,5.2
22,Brooklyn Community District 11,311,Brooklyn,54.8,0.8,47.3,1.3,41.2,1.0,40.0,...,50.6,1.6,30.2,0.8,4.1,0.3,46.1,1.3,1020,4.9
23,Brooklyn Community District 12,312,Brooklyn,35.4,0.8,36.7,1.2,60.3,2.3,22.5,...,57.9,1.6,28.9,0.8,3.3,0.3,38.5,1.2,879,4.0
24,Brooklyn Community District 13,313,Brooklyn,53.1,1.0,45.5,1.6,53.8,9.8,16.9,...,45.5,2.1,37.5,1.3,4.4,0.6,47.0,2.2,924,7.3
25,Brooklyn Community District 14,314,Brooklyn,41.7,0.9,24.2,1.1,40.4,32.8,9.6,...,48.5,1.5,37.0,0.8,4.2,0.4,42.9,1.2,1163,5.9
26,Brooklyn Community District 15,315,Brooklyn,50.5,0.8,37.2,1.2,65.2,3.5,18.3,...,48.4,1.7,40.9,0.9,3.6,0.3,46.4,1.4,1067,5.4
27,Brooklyn Community District 16,316,Brooklyn,30.7,1.2,9.0,0.9,2.8,73.6,1.4,...,54.3,2.2,15.8,1.0,6.7,0.7,47.8,3.1,1448,14.3
28,Brooklyn Community District 17,317,Brooklyn,51.4,1.0,9.2,0.7,3.1,85.3,1.6,...,49.1,1.7,24.5,0.9,4.7,0.4,47.7,1.6,1475,8.4
29,Brooklyn Community District 18,318,Brooklyn,39.8,0.7,12.0,0.6,22.5,61.7,4.9,...,41.7,1.9,31.2,0.7,4.2,0.3,48.5,1.3,1498,6.6
30,Manhattan Community District 1,101,Manhattan,28.1,1.5,9.6,1.1,64.8,3.2,20.9,...,28.4,2.2,78.8,1.2,2.7,0.5,26.1,1.2,1055,14.0
31,Manhattan Community District 2,102,Manhattan,21.5,1.3,6.1,0.7,74.4,1.9,14.1,...,33.4,2.2,80.4,1.4,2.9,0.5,24.9,1.0,2313,26.1
32,Manhattan Community District 3,103,Manhattan,34.5,1.1,28.1,1.2,33.3,8.4,30.6,...,38.4,1.8,43.3,1.2,3.6,0.4,31.3,1.3,2360,15.2
33,Manhattan Community District 4,104,Manhattan,31.8,1.5,11.9,1.1,55.2,6.3,16.7,...,33.6,2.1,71.2,1.4,3.6,0.6,27.8,1.2,2792,21.5
34,Manhattan Community District 5,105,Manhattan,26.4,1.4,6.4,1.0,67.5,3.3,19.2,...,33.2,2.3,82.3,1.4,3.2,0.6,24.0,1.1,4538,59.4
35,Manhattan Community District 6,106,Manhattan,24.9,1.2,6.8,0.9,68.2,3.7,17.7,...,35.2,2.2,80.3,1.2,2.5,0.4,27.5,1.1,1715,10.7
36,Manhattan Community District 7,107,Manhattan,22.9,1.1,9.2,0.9,65.9,6.1,9.3,...,32.3,1.9,75.3,1.0,3.3,0.4,32.4,1.1,1860,8.8
37,Manhattan Community District 8,108,Manhattan,23.6,1.4,5.4,0.7,75.3,2.3,10.2,...,32.5,2.0,80.5,1.2,2.0,0.3,31.4,1.1,2192,10.2
38,Manhattan Community District 9,109,Manhattan,34.9,1.5,19.3,1.4,25.6,22.6,8.3,...,45.4,2.3,43.9,1.6,3.8,0.6,36.7,1.9,1450,12.9
39,Manhattan Community District 10,110,Manhattan,24.7,1.3,12.4,1.1,14.4,53.2,3.3,...,39.0,1.7,39.0,1.2,6.2,0.6,37.4,1.5,1950,13.2
40,Manhattan Community District 11,111,Manhattan,23.5,1.2,18.9,1.2,13.7,31.6,7.6,...,38.5,1.8,31.3,1.3,5.2,0.6,35.5,1.8,1934,15.1
41,Manhattan Community District 12,112,Manhattan,46.7,1.3,37.0,1.4,19.5,7.2,3.2,...,43.3,1.6,33.9,1.0,6.0,0.6,41.0,1.7,1981,9.5
42,Queens Community District 1,401,Queens,39.1,0.9,23.3,0.9,46.4,8.5,15.3,...,37.6,1.4,44.4,0.9,4.2,0.4,40.0,1.1,1821,10.1
43,Queens Community District 2,402,Queens,53.4,1.2,38.7,1.6,26.7,3.8,35.5,...,41.5,1.8,38.4,1.0,3.3,0.4,37.6,1.4,954,6.4
44,Queens Community District 3,403,Queens,58.8,1.0,48.6,1.3,12.2,5.0,16.9,...,52.7,2.0,20.9,0.8,3.4,0.3,42.8,1.7,1456,7.8
45,Queens Community District 4,404,Queens,63.8,0.9,52.3,1.4,6.1,4.9,32.2,...,54.0,1.9,21.5,0.9,3.1,0.3,43.6,1.7,1209,5.9
46,Queens Community District 5,405,Queens,40.0,1.0,24.3,1.0,50.7,1.4,9.9,...,40.4,1.7,28.3,0.8,3.4,0.3,42.4,1.3,1320,7.0
47,Queens Community District 6,406,Queens,48.5,1.2,25.2,1.2,48.1,3.3,28.0,...,42.7,2.1,55.8,1.1,2.8,0.4,43.7,1.4,516,4.0
48,Queens Community District 7,407,Queens,56.3,0.8,52.4,1.3,25.9,2.0,52.2,...,56.7,1.8,26.8,0.7,2.5,0.2,41.0,1.2,1883,7.3
49,Queens Community District 8,408,Queens,47.6,1.1,28.2,1.4,27.8,12.1,34.7,...,48.5,2.3,38.3,1.1,5.2,0.5,44.3,1.6,1194,6.7
50,Queens Community District 9,409,Queens,51.0,0.9,26.4,1.0,17.3,5.8,27.4,...,47.8,1.9,26.5,0.8,4.3,0.3,46.4,1.4,712,4.4
51,Queens Community District 10,410,Queens,45.2,1.2,13.7,0.9,21.6,13.9,24.0,...,50.0,3.2,22.3,1.1,4.8,0.4,46.2,1.8,1148,8.3
52,Queens Community District 11,411,Queens,43.7,1.0,31.7,1.4,39.6,1.8,45.3,...,43.6,2.9,42.1,1.1,2.7,0.4,44.3,1.6,692,5.4
53,Queens Community District 12,412,Queens,43.2,0.8,15.4,0.9,2.6,59.5,14.2,...,47.1,1.7,22.5,0.7,5.9,0.4,48.6,1.4,2670,9.8
54,Queens Community District 13,413,Queens,42.4,0.9,13.1,0.8,10.7,55.6,15.6,...,43.5,2.5,29.6,0.8,4.4,0.3,47.4,1.4,1572,7.5
55,Queens Community District 14,414,Queens,26.7,1.3,12.5,1.2,34.2,35.8,3.8,...,42.0,2.5,29.8,1.4,5.1,0.7,51.1,2.9,1289,10.2
56,Staten Island Community District 1,501,Staten Island,25.4,1.1,12.4,0.8,38.8,20.3,9.2,...,50.7,2.5,31.7,1.0,2.9,0.4,43.6,1.8,1283,7.1
57,Staten Island Community District 2,502,Staten Island,28.5,1.1,13.8,1.0,66.3,4.1,13.2,...,44.8,3.5,32.8,1.2,2.8,0.3,43.8,1.8,597,4.1
58,Staten Island Community District 3,503,Staten Island,15.9,0.9,7.0,0.6,82.9,1.1,4.5,...,40.8,4.0,34.1,1.3,2.8,0.3,45.8,1.6,425,2.5

In [ ]:
filtered_data = population_data[population_data['cd_name'] == 'Queens Community District 1']
filtered_data

,cd_name,cd_number,borough,pct_foreign_born,moe_foreign_born,lep_rate,moe_lep_rate,pct_white_nh,pct_black_nh,pct_asian_nh,...,pct_hh_rent_burd,moe_hh_rent_burd,pct_bach_deg,moe_bach_deg,unemployment,moe_unemployment,mean_commute,moe_mean_commute,crime_count,crime_per_1000
42,Queens Community District 1,401,Queens,39.1,0.9,23.3,0.9,46.4,8.5,15.3,...,37.6,1.4,44.4,0.9,4.2,0.4,40.0,1.1,1821,10.1

In [ ]:
poplution_df=filtered_data[['pct_white_nh','pct_black_nh','pct_asian_nh','pct_other_nh','pct_hispanic']]

In [ ]:
poplution_df = poplution_df.rename(columns={
    'pct_white_nh': 'white',
    'pct_black_nh': 'black',
    'pct_asian_nh': 'asian',
    'pct_other_nh': 'other',
    'pct_hispanic': 'hispanic'
})
poplution_df

    white  black  asian  other  hispanic
42   46.4    8.5   15.3    2.9      26.9

In [ ]:
import pandas as pd

population_df = poplution_df[['white', 'black', 'asian', 'hispanic', 'other']]

population_df

    white  black  asian  hispanic  other
42   46.4    8.5   15.3      26.9    2.9

In [ ]:
sample_df

,White alone,Hispanic,Asian alone,Black or African American alone,Other
0,0.27451,0.254902,0.196078,0.156863,0.117647

In [ ]:
error_range=10
global error_range

In [ ]:
def comparison_engine(sample_df, population_df, error_range):
    for (pop_index, pop_row), (sample_index, sample_row) in zip(population_df.iterrows(), sample_df.iterrows()):
        white_pop = pop_row['white']
        black_pop = pop_row['black']
        asian_pop = pop_row['asian']
        hispanic_pop = pop_row['hispanic']
        other_pop = pop_row['other']

        white_sample = sample_row['White alone']
        hispanic_sample = sample_row['Hispanic']
        asian_sample = sample_row['Asian alone']
        black_sample = sample_row['Black or African American alone']
        other_sample = sample_row['Other']

        if (white_pop - 100*white_sample) > error_range:
            print("Population White is greater than Sample White. We need to conduct more surveys with white individuals.")
        elif (white_pop - 100*white_sample) < -error_range:
            print("Population White is smaller than Sample White. We need to conduct fewer surveys with white individuals.")
        else:
            print("The survey conducted among white individuals is just right.")


        if (black_pop - 100*black_sample) > error_range:
            print("Population Black is greater than Sample Black. We need to conduct more surveys with Black individuals.")
        elif (black_pop - 100*black_sample) < -error_range:
            print("Population Black is smaller than Sample Black. We need to conduct fewer surveys with Black individuals.")
        else:
            print("The survey conducted among Black individuals is just right.")

        if (asian_pop - 100*asian_sample) > error_range:
            print("Population Asian is greater than Sample Asian. We need to conduct more surveys with Asian individuals.")
        elif (asian_pop - 100*asian_sample) < -error_range:
            print("Population Asian is smaller than Sample Asian. We need to conduct fewer surveys with Asian individuals.")
        else:
            print("The survey conducted among Asian individuals is just right.")

        if (hispanic_pop - 100*hispanic_sample) > error_range:
            print("Population Hispanic is greater than Sample Hispanic. We need to conduct more surveys with Hispanic individuals.")
        elif (hispanic_pop - 100*hispanic_sample) < -error_range:
            print("Population Hispanic is smaller than Sample Hispanic. We need to conduct fewer surveys with Hispanic individuals.")
        else:
            print("The survey conducted among Hispanic individuals is just right.")

        if (other_pop - 100*other_sample) > error_range:
            print("Population Other is greater than Sample Other. We need to conduct more surveys with Other individuals.")
        elif (other_pop - 100*other_sample) < -error_range:
            print("Population Other is smaller than Sample Other. We need to conduct fewer surveys with Other individuals.")
        else:
            print("The survey conducted among Other individuals is just right.")

In [ ]:
comparison_engine(sample_df, population_df,100)

The survey conducted among white individuals is just right.
The survey conducted among Black individuals is just right.
The survey conducted among Asian individuals is just right.
The survey conducted among Hispanic individuals is just right.
The survey conducted among Other individuals is just right.

##Calculated standard error:
The standard error is used to measure the confidence of the sample scale, calculated by the formula: Standard error = sqrt(sample scale x(1-current scale)/ current size)4. Calculate the z-score:
The z-score is calculated using the standard error, which is the sample proportion minus the census proportion divided by the standard error z-score =(sample proportion - census proportion)/ standard error

In [ ]:
population_df = population_df.rename(columns={
    'white': 'White alone',
    'black': 'Black or African American alone',
    'asian': 'Asian alone',
    'hispanic': 'Hispanic',
    'other': 'Other'
})

In [ ]:
import math

standard_errors = pd.DataFrame(index=population_df.index, columns=population_df.columns)

for index, row in population_df.iterrows():
    population_size = sum(row)
    for column in population_df.columns:
        sample_proportion = sample_df[column].values[0]
        standard_error = math.sqrt((sample_proportion * (1 - sample_proportion)) / population_size)
        standard_errors.loc[index, column] = standard_error

In [ ]:
z_scores = pd.DataFrame(index=population_df.index, columns=population_df.columns)

for index, row in population_df.iterrows():
    for column in population_df.columns:
        population_proportion = row[column]/100
        sample_proportion = sample_df[column].values[0]
        standard_error = standard_errors.loc[index, column]
        z_score = (sample_proportion - population_proportion) / standard_error
        z_scores.loc[index, column] = z_score

In [ ]:
print("Standard Errors:")
print(standard_errors)
print("\nZ-Scores:")
print(z_scores)

Standard Errors:
   White alone Black or African American alone Asian alone  Hispanic     Other
42    0.044627                        0.036367    0.039703  0.043581  0.032219

Z-Scores:
    White alone Black or African American alone Asian alone    Hispanic  \
42 -1033.584987                     -229.414066 -380.424381 -611.397983

       Other
42 -86.35761

##Set the significance level:

In [ ]:
import pandas as pd
from scipy import stats

# Set the significance level to 0.05
alpha = 0.05

# Calculate the maximum error probability for accepting the null hypothesis
# Since we are using a one-tailed test, divide the significance level by 2
max_error_probability = alpha / 2

# Check if each sample's Z-score exceeds the significance level
for index, row in z_scores.iterrows():
    for column in z_scores.columns:
        z_score = z_scores.loc[index, column]

        # Look up the critical value in the Z-table (standard normal distribution table)
        # If the calculated Z-score is greater than the critical value, reject the null hypothesis
        # This indicates a significant difference between the category proportion in the sample data and the population data
        if z_score > stats.norm.ppf(1 - max_error_probability):
            print(f"The proportion of {index} category in feature {column} significantly differs from the population proportion.")
        else:
            # If the calculated Z-score is less than or equal to the critical value, fail to reject the null hypothesis
            # This indicates no significant difference between the category proportion in the sample data and the population data
            print(f"The proportion of {index} category in feature {column} does not significantly differ from the population proportion.")

The proportion of 42 category in feature White alone does not significantly differ from the population proportion.
The proportion of 42 category in feature Black or African American alone does not significantly differ from the population proportion.
The proportion of 42 category in feature Asian alone does not significantly differ from the population proportion.
The proportion of 42 category in feature Hispanic does not significantly differ from the population proportion.
The proportion of 42 category in feature Other does not significantly differ from the population proportion.